trigger:
- main

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: $(vmImageName)
      steps:
      - script: |
          wget https://dist.ballerina.io/downloads/2201.1.0/ballerina-2201.1.0.zip
          unzip -d /opt ballerina-2201.1.0.zip
          /opt/ballerina-2201.1.0/bin/ballerina build main.bal
        displayName: 'Download and install Ballerina SDK'
